"""empty message

Revision ID: 10e07739c08
Revises: 426c7159599
Create Date: 2015-03-24 00:03:48.608810

"""

# revision identifiers, used by Alembic.
revision = '10e07739c08'
down_revision = '426c7159599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
