"""empty message

Revision ID: 14ca38dc6aa2
Revises: 169ff636d229
Create Date: 2015-03-21 13:14:45.387511

"""

# revision identifiers, used by Alembic.
revision = '14ca38dc6aa2'
down_revision = '169ff636d229'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msm_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairing_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msu_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('team')
    op.drop_table('question_smm')
    op.drop_table('question_smu')
    op.add_column('answers', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('question_cod', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_constraint(u'answers_pregunta_cod_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'question_model', ['question_cod'], ['cod'])
    op.drop_column('answers', 'pregunta_cod')
    op.drop_column('answers', 'estado')
    op.add_column('question_model', sa.Column('image', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_model', 'image')
    op.add_column('answers', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('pregunta_cod', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(u'answers_pregunta_cod_fkey', 'answers', 'question_model', ['pregunta_cod'], ['cod'])
    op.drop_column('answers', 'state')
    op.drop_column('answers', 'question_cod')
    op.drop_column('answers', 'image')
    op.create_table('question_smu',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'question_model.cod'], name=u'question_smu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'question_smu_pkey')
    )
    op.create_table('question_smm',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'question_model.cod'], name=u'question_smm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'question_smm_pkey')
    )
    op.create_table('team',
    sa.Column('username', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('username', name=u'team_pkey')
    )
    op.drop_table('msu_question')
    op.drop_table('pairing_question')
    op.drop_table('msm_question')
    ### end Alembic commands ###
