"""empty message

Revision ID: 1a9ad7d690ca
Revises: 26db6ad5aac4
Create Date: 2015-05-14 17:30:22.900000

"""

# revision identifiers, used by Alembic.
revision = '1a9ad7d690ca'
down_revision = '26db6ad5aac4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpvideos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'helpequations', ['id'])
    op.create_unique_constraint(None, 'helptheory', ['id'])
    op.add_column(u'question', sa.Column('title', sa.String(length=70), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'question', 'title')
    op.drop_constraint(None, 'helptheory', type_='unique')
    op.drop_constraint(None, 'helpequations', type_='unique')
    op.drop_table('helpvideos')
    ### end Alembic commands ###
