"""empty message

Revision ID: 1d3ccb8c16fb
Revises: 35cac1c949e3
Create Date: 2015-04-19 21:19:58.412412

"""

# revision identifiers, used by Alembic.
revision = '1d3ccb8c16fb'
down_revision = '35cac1c949e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('max_score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'max_score')
    ### end Alembic commands ###
