"""empty message

Revision ID: 235d18cd1d4
Revises: 2ea72ae8df46
Create Date: 2015-03-24 00:13:55.678632

"""

# revision identifiers, used by Alembic.
revision = '235d18cd1d4'
down_revision = '2ea72ae8df46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('types', sa.String(length=50), nullable=True))
    op.drop_column('question', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('question', 'types')
    ### end Alembic commands ###
