"""empty message

Revision ID: 2a809f98c39b
Revises: 771b6f55c83
Create Date: 2015-03-14 12:38:50.784778

"""

# revision identifiers, used by Alembic.
revision = '2a809f98c39b'
down_revision = '771b6f55c83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('icon', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'topic', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='unique')
    op.drop_column('topic', 'icon')
    ### end Alembic commands ###
