"""empty message

Revision ID: 37a8097cc244
Revises: 4a008022b9ad
Create Date: 2015-06-02 09:41:36.161000

"""

# revision identifiers, used by Alembic.
revision = '37a8097cc244'
down_revision = '4a008022b9ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'type')
    ### end Alembic commands ###
