"""empty message

Revision ID: 3b1c20905d46
Revises: 28854df1861b
Create Date: 2015-06-02 09:05:01.414000

"""

# revision identifiers, used by Alembic.
revision = '3b1c20905d46'
down_revision = '28854df1861b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('user_username', sa.String(length=15), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    ### end Alembic commands ###
