"""empty message

Revision ID: 3c5ac9afd06e
Revises: 479354089585
Create Date: 2015-04-18 11:25:21.444238

"""

# revision identifiers, used by Alembic.
revision = '3c5ac9afd06e'
down_revision = '479354089585'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=15), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column(u'user', sa.Column('cur_topic_id', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('life', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('tw_username', sa.String(length=200), nullable=True))
    op.add_column(u'user', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'user', 'topic', ['cur_topic_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'type')
    op.drop_column(u'user', 'tw_username')
    op.drop_column(u'user', 'life')
    op.drop_column(u'user', 'cur_topic_id')
    op.drop_table('userscore')
    ### end Alembic commands ###
