"""empty message

Revision ID: 45f96e9606c4
Revises: 415e32c5a9f7
Create Date: 2015-03-14 11:34:42.324112

"""

# revision identifiers, used by Alembic.
revision = '45f96e9606c4'
down_revision = '415e32c5a9f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_model',
    sa.Column('cod', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cod')
    )
    op.create_table('answers',
    sa.Column('cod', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pregunta_cod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_cod'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('cod'),
    sa.UniqueConstraint('cod')
    )
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('answers')
    op.drop_table('question_model')
    ### end Alembic commands ###
