"""empty message

Revision ID: 46b5a1643f1b
Revises: 15de980f1406
Create Date: 2015-03-21 13:50:44.789340

"""

# revision identifiers, used by Alembic.
revision = '46b5a1643f1b'
down_revision = '15de980f1406'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasification_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clasification_question')
    ### end Alembic commands ###
