"""empty message

Revision ID: 47b90040283d
Revises: None
Create Date: 2015-03-11 16:08:42.223480

"""

# revision identifiers, used by Alembic.
revision = '47b90040283d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('username', sa.String(length=140), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    ### end Alembic commands ###
