"""empty message

Revision ID: 484c36d4a426
Revises: 4e8812aaff94
Create Date: 2015-03-15 23:42:33.241080

"""

# revision identifiers, used by Alembic.
revision = '484c36d4a426'
down_revision = '4e8812aaff94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_smu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_smu')
    ### end Alembic commands ###
