"""empty message

Revision ID: 4bd93db41246
Revises: 2d9e9c148829
Create Date: 2015-06-02 08:17:43.762000

"""

# revision identifiers, used by Alembic.
revision = '4bd93db41246'
down_revision = '2d9e9c148829'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    ### end Alembic commands ###
