"""empty message

Revision ID: 4c5fab77a06e
Revises: 1709179fce77
Create Date: 2015-03-14 12:23:51.936521

"""

# revision identifiers, used by Alembic.
revision = '4c5fab77a06e'
down_revision = '1709179fce77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'answers', ['cod'])
    op.add_column(u'question_model', sa.Column('topic_cod', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'question_model', ['cod'])
    op.create_foreign_key(None, 'question_model', 'topic', ['topic_cod'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_model', type_='foreignkey')
    op.drop_constraint(None, 'question_model', type_='unique')
    op.drop_column(u'question_model', 'topic_cod')
    op.drop_constraint(None, 'answers', type_='unique')
    op.drop_table('topic')
    ### end Alembic commands ###
