"""empty message

Revision ID: 4de7d3c1a9cb
Revises: 15b33cbb9d84
Create Date: 2015-03-21 13:23:44.403576

"""

# revision identifiers, used by Alembic.
revision = '4de7d3c1a9cb'
down_revision = '15b33cbb9d84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completation_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_model.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_completation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_completation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'question_model.cod'], name=u'question_completation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'question_completation_pkey')
    )
    op.drop_table('completation_question')
    ### end Alembic commands ###
