"""empty message

Revision ID: 50366d7ed9ab
Revises: 858fe862488
Create Date: 2015-06-02 09:12:07.119000

"""

# revision identifiers, used by Alembic.
revision = '50366d7ed9ab'
down_revision = '858fe862488'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
