"""empty message

Revision ID: 58db53cff914
Revises: 93d74f1d9d2
Create Date: 2015-03-14 13:51:15.413815

"""

# revision identifiers, used by Alembic.
revision = '58db53cff914'
down_revision = '93d74f1d9d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
