"""empty message

Revision ID: 5961623a1c0a
Revises: 5110a19d699b
Create Date: 2015-05-15 17:35:45.165000

"""

# revision identifiers, used by Alembic.
revision = '5961623a1c0a'
down_revision = '5110a19d699b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'helpvideos', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'helpvideos', type_='unique')
    op.drop_table('helpreport')
    ### end Alembic commands ###
