"""empty message

Revision ID: 5f98a89c38b
Revises: 17116e311ae6
Create Date: 2015-06-02 08:25:38.476000

"""

# revision identifiers, used by Alembic.
revision = '5f98a89c38b'
down_revision = '17116e311ae6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_username', sa.String(length=15), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
