"""empty message

Revision ID: 66b8ba2d1c2
Revises: b70e423deef
Create Date: 2015-05-09 09:38:53.970271

"""

# revision identifiers, used by Alembic.
revision = '66b8ba2d1c2'
down_revision = 'b70e423deef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helptheory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('helpequations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equation', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helpequations')
    op.drop_table('helptheory')
    ### end Alembic commands ###
