"""empty message

Revision ID: c054d9cb9b4
Revises: 2ab00d3effc8
Create Date: 2015-06-01 07:48:44.839000

"""

# revision identifiers, used by Alembic.
revision = 'c054d9cb9b4'
down_revision = '2ab00d3effc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'helpreport', ['id'])
    op.add_column('user', sa.Column('social_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['social_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'social_id')
    op.drop_constraint(None, 'helpreport', type_='unique')
    ### end Alembic commands ###
