"""empty message

Revision ID: e507e608ee3
Revises: 825c4f84641
Create Date: 2015-03-24 00:06:31.679401

"""

# revision identifiers, used by Alembic.
revision = 'e507e608ee3'
down_revision = '825c4f84641'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
