"""empty message

Revision ID: fafeeea127a
Revises: 49bb1206b05d
Create Date: 2015-03-24 00:15:04.409176

"""

# revision identifiers, used by Alembic.
revision = 'fafeeea127a'
down_revision = '49bb1206b05d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('question', 'types')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('types', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('question', 'type')
    ### end Alembic commands ###
